before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: sd0ASa7WoUVJmrlsPVwS0wL88Di75/WDEDLte0mpmVCWDA+oZXlMg3aSA6l9GjUlba9ozasxFReSKXs3Pk3tCrAloGMbekWQo5I6No3tRLwO48miBiV6Yu72FmbLVv8cnYDvdNZwADViEmoCFMM6Daw9EIFLop8EJ+ZM4Q3BCph6N0bbBhcx11JNi08KDDNw2kcv1381jZ0HfOEEYC8WPPpieNqUYz/XhmXofV5qPDoX/un5LWv2Gh8K+DRRQ4ZAuJa2I/cG0/yDqle7qbC24l9hHU/HJBgkwHlZp/mGSmhCLt2FScHeF2HRw2jNI7l+q6qTvecaTJ+TVV5MK/M2nS4CZ3hOWZCQ/5PURVgsHUjln8AD+zqXYHru3a+HmCKDcDCcmFIRgkP6mIbtX81X/MI4InwCVcRYRtbMWVcmpOdjXO0w8a9k4lmrJ+pxAcwSlIzib4WPNdMVA2AjHMeHMXGV5jgJea7+7vhKuZm8GCWwFB0+CwGb3PyY3lrJp+laqIHk3k6nMwbK9eUNr1kknSuGuzKKvylm9c8SNbMpBovkVrz0746oFrEnYn/TP0/Ht+WSXuo84g631lIp9Kfmvjjz4ve6ZSH4Ij+Jtb+ujQvgOw8EcBjhu/CbjReNcvRL/jbKj0yOrGLWibfazNCTMOWf6K3sfKWdEUJU1irm8Bc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
